version: "3"

volumes:
  data-base:

services:
  db:
    image: postgres
    volumes:
      - "data-base:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/unison
    ports:
      - "3000:3000"
    depends_on:
      - db
